name: PathSenseUIKitSample
options:
  bundleIdPrefix: com.dayushmand.pathsense.sample
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "14.3"

packages:
  PathSenseSDK:
    path: "../../ios/PathSenseSDK"

targets:
  PathSenseUIKitSample:
    type: application
    platform: iOS
    sources:
      - PathSenseUIKitSample
    dependencies:
      - package: PathSenseSDK
        product: PathSenseUI
    settings:
      base:
        CODE_SIGN_IDENTITY: "-"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        SWIFT_VERSION: "5.0"
    info:
      path: PathSenseUIKitSample/Info.plist
      properties:
        CFBundleDisplayName: PathSense UIKit Sample
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
